### ISSUE TITLE
一些修改建议

### ISSUE THREAD

**Issue by liudangyi** [n0wa11/gfw_whitelist#20]
1. 自动化不够，现在是完全手工处理那么多域名，其实可以根据 IP 判断是否在国内来决定是否放在白名单里。
2. 重复条目过多，而且顺序比较杂乱。
3. 通用程度不够，见 #19 。同时建议将所有域名分为两种，一种是直接解析到国内的，可以用 1 中的方法自动判断；另一种是国内访问较快的，这部分可以手工管理。

**Comment by n0wa11** [comment]
请提供一个 pull request。
