### ISSUE TITLE
加个1080端口的pac吧，用SS客户端是1080端口

### ISSUE THREAD

**Issue by laoyuan** [n0wa11/gfw_whitelist#23]
或者干脆把端口作为动态参数靠谱么？刚开始用github不知道支不支持

**Comment by cnDelbert** [comment]
shadowsocks 客户端都可以自己配置端口的，只不过大部分人习惯1080，因为@clowwindy 一开始用的1080吧。
命令行的也都可以直接在json里面配置的。

**Comment by laoyuan** [comment]
mac 客户端没找到在哪设端口啊

**Comment by cnDelbert** [comment]
我回去看一下，现在在实验室。

**Comment by cnDelbert** [comment]
果然……没有本地端口这一项……
要是不行的话，用sslocal命令吧……

**Comment by n0wa11** [comment]
请提供一个 pull request。
